version: 2.1

executors:
  node_image:
    docker:
      - image: cimg/node:lts

commands:
  update_version:
    description: Will update package.json with tag of the commit
    steps:
      - run:
          name: Update version
          command: |
            if [[ ! -z ${CIRCLE_TAG} ]];
            then
              npm version --no-git-tag-version $CIRCLE_TAG
            fi
  install_dependencies:
    description: Will install dependencies
    steps:
      - run:
          name: Install
          command: npm ci
  compile:
    description: Will compile
    steps:
      - run:
          name: Compile
          command: npm run compile
      - run:
          name: Compile web
          command: npm run compile-web
  vsce_package:
    description: Package vscode extension
    steps:
      - run:
          name: Package vscode extension
          command: npm run package
  vsce_publish:
    description: Publish to marketplace
    steps:
      - run:
          name: Publish to marketplace
          command: |
            export VSCE_PAT=$VS_TOKEN
            npm run deploy
jobs:
  build:
    executor: node_image
    steps:
      - checkout
      - update_version
      - install_dependencies
      - compile
      - vsce_package

workflows:
  build-n-deploy:
    jobs:
      - build:
          name: build
          filters:
            tags:
              ignore: /^(\*|\d+(\.\d+){0,2}(\.\*)?)$/
      - build:
          name: build and publish
          post-steps:
            - vsce_publish
          filters:
            tags:
              only: /^(\*|\d+(\.\d+){0,2}(\.\*)?)$/
            branches:
              ignore: /.*/
