version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Restore dependencies
          command: npm install
      - run:
          name: Compile
          command: npm run compile
      - run:
          name: install VS Code Extension Manager
          command: npm i vsce -g
      - run:
          name: publish to marketplace
          command: vsce publish -p $VSTOKEN

workflows:
  build-deploy:
    jobs:
      - build:
          name: build
          filters:
            branches:
              only:
                - master
      # - deploy:
      #     name: deploy-test
      #     requires:
      #       - build