version: 2.1

executors:
  node_image:
    docker:
      - image: cimg/node:lts

commands:
  update_version:
    description: Will update package.json with tag of the commit
    steps:
      - run:
          name: Update version
          command: |
            if [[ ! -z ${CIRCLE_TAG} ]];
            then
              sed -i -e "s?1.0.0?$CIRCLE_TAG?g" ./package.json
            fi
  install_dependencies:
    description: Will install dependencies
    steps:
      - run:
          name: Install
          command: npm ci
  compile:
    description: Will compile
    steps:
      - run:
          name: Compile
          command: npm run compile
  vsce_install:
    description: Install VS Code Extension Manager
    steps:
      - run:
          name: Install VS Code Extension Manager
          command: npm install --prefix=$HOME/.local --global vsce
  vsce_package:
    description: Package vscode extension
    steps:
      - run:
          name: Package vscode extension
          command: |
            export VSCE_PAT="debug"
            vsce package
  vsce_publish:
    description: Publish to marketplace
    steps:
      - run:
          name: Publish to marketplace
          command: vsce publish -p $VS_TOKEN

jobs:
  build:
    executor: node_image
    steps:
      - checkout
      - update_version
      - install_dependencies
      - compile
      - vsce_install
      - run:
          name: debug stuff
          command: |
            node --version
            vsce --version
      - vsce_package

workflows:
  build-n-deploy:
    jobs:
      - build:
          name: build
          filters:
            tags:
              ignore: /^(\*|\d+(\.\d+){0,2}(\.\*)?)$/
      - build:
          name: build and publish
          post-steps:
            - vsce_publish
          filters:
            tags:
              only: /^(\*|\d+(\.\d+){0,2}(\.\*)?)$/
            branches:
              ignore: /.*/
