version: 2.1

executors:
  node_image:
    docker:
      - image: circleci/node:latest

commands:
  install_envsubst:
    description: Will install the package envsubst
    steps:
      - run:
          name: Install envsubst
          command: |
            sudo apt install gettext
  update_version:
    description: Will update package.json with tag of the commit
    steps:
      - run:
          name: Update version
          command: |
            cat ./package.json
            envsubst < ./package.json > ./package_var.json
            rm ./package.json
            mv ./package_var.json ./package.json
            cat ./package.json
  install_dependencies:
    description: Will install dependencies
    steps:
      - run:
          name: Install
          command: npm install
  compile:
    description: Will compile
    steps:
      - run:
          name: Compile
          command: npm run compile
  vsce_install:
    description: Install VS Code Extension Manager
    steps:
      - run:
          name: Install VS Code Extension Manager
          command: sudo npm i vsce -g
  vsce_package:
    description: Packge vscode extension
    steps:
      - run:
          name: Packge vscode extension
          command: vsce package
  vsce_publish:
    description: Publish to marketplace
    steps:
      - run:
          name: Publish to marketplace
          command: vsce publish -p $VS_TOKEN

jobs:
  test:
    executor: node_image
    steps:
      - checkout
      - install_envsubst
      - update_version
      - install_dependencies
      - compile
  build:
    executor: node_image
    steps:
      - checkout
      - install_envsubst
      - update_version
      - install_dependencies
      - compile
      - vsce_install
      - vsce_package
      - vsce_publish

workflows:
  test-deploy:
    jobs:
      - test:
          name: test
          filters:
            tags:
              only: /.*/
      - build:
          name: build
          requires:
            - test
          filters:
            tags:
              only: /^(\*|\d+(\.\d+){0,2}(\.\*)?)$/
            branches:
              ignore: /.*/
