version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Update version
          command: |
            envsubst < ./package.json > ./package_var.json
            rm ./package.json
            mv ./package_var.json ./package.json
      - run:
          name: Install
          command: npm install
      - run:
          name: Compile
          command: npm run compile
      - run:
          name: Install VS Code Extension Manager
          command: sudo npm i vsce -g
      - run:
          name: Package extension
          command: vsce package
      - run:
          name: Publish to marketplace
          command: vsce publish -p $VS_TOKEN

workflows:
  build-deploy:
    jobs:
      - build:
          name: build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^(\*|\d+(\.\d+){0,2}(\.\*)?)$/
